### ISSUE TITLE
Proposal: Separate GOPATH for each tool

### ISSUE THREAD

**Issue by crxpandion** [twitchtv/retool#17]
Say I have a tool `shovel` and a tool `rake`. Both of these tools depend on different versions of package `metal_head`. In the current implementation this would fail to build from a clean install simultaneously. 

# Proposal
This is due to retool being different from the traditional vendor problem: rather than building from a single package tree, `retool` can build multiple binaries from a collection of trees. In its current model these trees can share sub trees or leaves which leads to the problem described above. 

I propose changing how retool collects and manipulates the `GOPATH` to be a one-to-one relationship between the tool and directory. To maintain ease of use there should continue to be a single `GOBIN` directory.

As a side benefit this proposal would also allow retool to not have to download all tools to sync with the manifest, as it could ask git for the current checked out sha.
# Implementation
Change tools dir structure, and cache dir, to be
```
_tools
├── bin
│   ├── shovel
│   └── rake
├── manifest.json
├── shovel
│   ├── pkg
│   │  └── linux_amd64
│   └── src
│      └── github.com
└── rake
    ├── pkg
    │  └── linux_amd64
    └── src
       └── github.com
```
Change the install command to set `GOBIN` appropriately, and keep track of each tools dir inside the tool struct.

**Comment by crxpandion** [comment]
This looks weird so there are probably improvements that could be made to the individual tool directory names.

**Comment by spenczar** [comment]
I like this idea a lot. It's kind of weird and will weird people out, but _tools is not supposed to be edited, really.

I see two advantages:
 1. We can add, upgrade, and remove a single tool at a time, which is a very big speed boost in some workflows.
 2. Since we build tools in their own trees, we don't have to worry about dependency conflicts across trees.

That first advantage is easy to implement. The second is not as easy, since the only way we capture it is if we add some way to pin the version of a dependency of a tool. That requires some extra design around tools.json and manifest.json.


There's one tangle to solve when implementing this: we set GOPATH to be `GOPATH=$GOPATH:$PWD/_tools` when executing commands. We basically do this for gometalinter support. Should we set GOPATH to `GOPATH=$GOPATH:$PWD/_tools/shovel:$PWD/_tools/rake`, etc? Yes, I think so.

**Comment by spenczar** [comment]
A more significant problem: on build machines without `retool` available, many people do `GOPATH=$PWD/_tools go install all` to bootstrap their tools. Supporting this is important, and it wouldn't work with a separate GOPATH per tool.

Maybe we could write a script into _tools which iterates over the tools and installs them all? Tough to do cross-platform, but it might fit the need.

**Comment by spenczar** [comment]
As mentioned in #19, this is too traumatic of a change for retool. It would break badly for users with an old installed version of retool who work on a project set up with the new version.

We need retool to understand the version of its manifest and lock file before attempting such a breaking change so we can appropriately warn users.
