### ISSUE TITLE
Undesired cleanup for runtime dependencies

### ISSUE THREAD

**Issue by jmp0xf** [twitchtv/retool#32]
eg.

https://github.com/volatiletech/sqlboiler

This command tool needs a set of template files to generate codes.

I know, things get much complicated if runtime dependencies are considered, so I am wondering is it possible to provide a way to indicate which kind of files/dir should not be dropped?

**Comment by spenczar** [comment]
Oof, we tried to fix this in https://github.com/twitchtv/retool/pull/25, but it appears the project has changed names.

We raised an issue about this at https://github.com/volatiletech/sqlboiler/issues/151, and I think the sqlboiler folks plan to avoid the runtime dependency by using gobindata, but we clearly need to fix this on our side in the short timeframe.

You mentioned "providing a way to flag dirs/files not to be dropped." I'm pretty wary of this. It would be hard to get right - you can do it with either flags passed to retool (`retool sync -no-prune=github.com/volatiletech/sqlboiler/templates`, maybe), or with a config file.

I am strongly against flags, because we would need to pass them to every subcommand that eventually can call `retool sync`, so it would need to be there for every `retool do` call. That's pretty tricky and would be hard to communicate to other people working on your project - everyone would need to look up the magic invocation to get it right. 

Putting it in the tools.json config file is an option, but the workflow would be weird: would you manually edit the config file to say "always keep _this_ particular subpackage," and then run `retool sync` manually to make it happen? I'm not sure - it's not an obvious experience, anyway. So, I'm moderately against that idea, too.

I would like to
