### ISSUE TITLE
Cleanup after sync break gometalinter vendored linters

### ISSUE THREAD

**Issue by krostar** [twitchtv/retool#7]
Hi,

I tried to use your tool and it works without any problems with some tools I use (govendor and goveralls) except [gometalinter](https://github.com/alecthomas/gometalinter).

As you can see, they use a `_linters` directory containing the different linters they support. The problem is that directory is cleaned by the [cleanup function called on tool sync](https://github.com/twitchtv/retool/blob/master/sync.go#L45), making gometalinter throwing `gometalinter: error: could not find vendored linters in GOPATH`. 

The only solutions I can see are:
- to disable the vendored linters feature with  `--vendored-linters=false`, but I didn't like because it implies gometalinter to fetch linters without controlling the version
- add a new flag like `retool add --cleaning=false github.com/alecthomas/gometalinter origin/master` which generate something like this
```
{
  "Tools": [
    {
      "Repository": "github.com/alecthomas/gometalinter",
      "Commit": "bae2f1293d092fd8167939d5108d1b025eaef9de",
      "Clean": false
    }
  ]
}
```
- remove the `s.cleanup()` line because who care to have useless files in the `_tools` directory ? It's not supposed to be in the VCS

Is there another solutions ? Can you do something about this ?
Thank you.

**Comment by spenczar** [comment]
Excellent bug report - thanks for figuring out the root cause.

I'd actually like a different option. `gometalinter` is widely used; I think we should special-case in support for it so users don't have to think. Practicality beats purity here. 

@alecthomas, do you foresee any changes to how `gometalinter` vendors its linters any time soon? Do you feel comfortable making any compatibility statements around it?  I could just preserve the `_linters` tree.

Or, if `gometalinter` wrote a manifest of the tools and versions it uses, `retool` could read that manifest and install them. I see one in https://github.com/alecthomas/gometalinter/blob/a1e22c348ee992e4bdddd5f4804bb30ec77e8b96/_linters/src/manifest - do you expect to keep using that manifest format?

@krostar In the short term, you could use `--vendored-linters=false` and then manually add linters with retool, like
```
retool add github.com/GoASTScanner/gas 1c8e7ff6861b2ee1c4d48a279b5eee07448baa5f
retool add github.com/alecthomas/gocyclo aa8f8b160214d8dfccfe3e17e578dd0fcc6fede7
```
etc for all the linters you want to use. This is definitely not a good long-term solution, but it could work for you while this gets figured out.

**Comment by alecthomas** [comment]
@spenczar no, linters will be vendored in this way from now on. I use gvt to vendor, which manages the manifest. The only potential change would be switching to the "dep" tool, but that is some time away.

**Comment by spenczar** [comment]
Great, thanks. Let's go with marking the `github.com/alecthomas/gometalinter/_linters` directory as special.
